
async function main() {

}
// handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
